# -*- coding: utf-8 -*-
"""
Created on Fri Jun  4 10:11:21 2021

@author: lvkexin
"""

import torch
import matplotlib.pyplot as plt

[loss, acc]=torch.load('Node1_loss_acc_fed_mutual_.pt', map_location=torch.device('cpu'))
#loss_node1=loss.get('1')
#print(loss_node1)
acc_node1=acc.get('1')
print(max(acc_node1))

[loss, acc]=torch.load('Node2_loss_acc_fed_mutual_.pt', map_location=torch.device('cpu'))
#loss_node2=loss.get('2')
acc_node2=acc.get('2')
print(max(acc_node2))
[loss, acc]=torch.load('Node3_loss_acc_fed_mutual_.pt', map_location=torch.device('cpu'))
acc_node3=acc.get('3')
#loss_node3=loss.get('3')
print(max(acc_node3))
[loss, acc]=torch.load('Node4_loss_acc_fed_mutual_.pt', map_location=torch.device('cpu'))
acc_node4=acc.get('4')
print(max(acc_node4))
#loss_node4=loss.get('4')
[loss, acc]=torch.load('Node5_loss_acc_fed_mutual_.pt', map_location=torch.device('cpu'))
acc_node5=acc.get('5')
print(max(acc_node5))
#loss_node5=loss.get('5')
#[loss, acc]=torch.load('Node6_loss_acc_normal_.pt', map_location=torch.device('cpu'))
#acc_node6=acc.get('6')
#print(max(acc_node6))
##loss_node6=loss.get('5')
#[loss, acc]=torch.load('Node7_loss_acc_normal_.pt', map_location=torch.device('cpu'))
#acc_node7=acc.get('7')
#print(max(acc_node7))
##loss_node5=loss.get('5')
#[loss, acc]=torch.load('Node8_loss_acc_normal_.pt', map_location=torch.device('cpu'))
#acc_node8=acc.get('8')
#print(max(acc_node8))
##loss_node5=loss.get('5')
#[loss, acc]=torch.load('Node9_loss_acc_normal_.pt', map_location=torch.device('cpu'))
#acc_node9=acc.get('9')
#print(max(acc_node9))
##loss_node5=loss.get('5')
#[loss, acc]=torch.load('Node10_loss_acc_normal_.pt', map_location=torch.device('cpu'))
#acc_node10=acc.get('10')
#print(max(acc_node10))
#loss_node5=loss.get('5')

#plt.plot(loss_node1,color="red", linewidth="1.5", linestyle="-")
#plt.plot(loss_node2,color="blue", linewidth="1.5", linestyle="--")
#plt.plot(loss_node3,color="purple", linewidth="1.5", linestyle="-.")
#plt.plot(loss_node4,color="green", linewidth="1.5", linestyle=":")
#plt.plot(loss_node5,color="black", linewidth="1.5", linestyle="dotted")
#plt.legend(["Node1-LeNet5","Node2-MLP",'Node3-CNN','Node4-ResNet18','Node5-CNN'])
#plt.xlabel('Iterations')
#plt.ylabel('Loss')
#plt.savefig('CDFL_loss.eps')
#plt.savefig('CDFL_loss.png')
#plt.show()
#
#plt.plot(acc_node1,color="red", linewidth="1.5", linestyle="-")
#plt.plot(acc_node2,color="blue", linewidth="1.5", linestyle="--")
#plt.plot(acc_node3,color="purple", linewidth="1.5", linestyle="-.")
#plt.plot(acc_node4,color="green", linewidth="1.5", linestyle=":")
#plt.plot(acc_node5,color="black", linewidth="1.5", linestyle="dotted")
#plt.legend(["Node1-LeNet5","Node2-MLP",'Node3-CNN','Node4-ResNet18','Node5-CNN'])
#plt.xlabel('Iterations')
#plt.ylabel('Accuracy (%)')
#plt.savefig('CDFL_acc.eps')
#plt.savefig('CDFL_acc.png')
#plt.show()